imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    csrf_protection: false
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: pdo_sqlite
        path: %kernel.cache_dir%/test.db
        charset: UTF8

security:
  firewalls:
    secured_area:
      pattern: ^/
      stateless: true
      http_basic:
        provider: in_memory
        realm: "Secured API Admin"