EtienneBlogBackendBundle:
    resource: "@EtienneBlogBackendBundle/Resources/config/routing.yml"
    prefix:   /api/

EtienneBlogBundle:
    resource: "@EtienneBlogBundle/Resources/config/routing.yml"
    prefix:   /
