security:
    firewalls:
      secured_api:
        pattern: ^/api/admin/
        stateless: true
        http_basic:
          provider: in_memory
          realm: "Secured API Area"

      secured_area:
        pattern:    ^/
        anonymous: ~
        form_login: ~
        logout:
          path: /logout
          target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/admin, roles: ROLE_ADMIN }

    providers:
        in_memory:
           memory:
            users:
              admin: { password: password, roles: 'ROLE_ADMIN' }

    encoders:
      Symfony\Component\Security\Core\User\User: plaintext